### ISSUE TITLE
JPRPのperldoc-jp/translationへの統合を行うため、もろもろのドキュメントを調整する

### ISSUE THREAD

**Issue by kfly8** [perldoc-jp/wg-perl-document#28]
## 背景

- https://github.com/perldoc-jp/wg-perl-document/issues/25
- JPRPのperldoc-jp/translationへの統合を行うため、もろもろのドキュメントを調整する

## TODO

- [x] http://perldocjp.osdn.jp/perldocjp-faq   JPRPのFAQ
  - -> translationのREADMEに統合する。CVS関連の情報は古いため削除でOK(FAQでない)
- [x] https://osdn.net/projects/perldocjp/docs/?category_id=0&language_id=2
  - -> perldocjp に参加するにはどうすれば良いか？については、translationのREADMEに統合する。CVS関連の情報は古いため削除でOK
- [x] https://perldoc.jp/manners 
  - -> JPRPに関して言及している箇所は、perldoc-jp/translation に書き換えるか、削除をする 
  - そもそも perldoc-jp/translation に置く方が良さそう。
- [x] https://perldoc.jp/about
  - -> perldoc.jp のサイトに関する説明は、最新の状態に書き換え
- [x] https://perldoc.jp/ トップページの調整
  - BEFORE: サイト内の翻訳データは、Japanized Perl Resources Project(JPRP)で翻訳されたもの、有志が翻訳しているgithubのリポジトリ、JPAの翻訳文書から取得しています。
  - AFTER: サイト内の翻訳データは、https://github.com/perldoc-jp/translation とJPAの翻訳文書から取得しています。

**Comment by kfly8** [comment]
https://github.com/perldoc-jp/perldoc.jp/pull/53 こちらで、perldoc.jpの aboutやトップの調整をした。
